# ----------------------------------------------------------------------------
#
# Package             : axon
# Source Repo         : https://github.com/tj/axon
# Travis Job Link     : https://travis-ci.com/github/santosh653/axon
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
  - amd64
  - ppc64le
  
language: node_js
node_js:
  - "6"
